---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: message-analysis-dev
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    backstage.io/app: message-analysis
spec:
  project: default
  source:
    repoURL: https://github.com/rhdh-demo-gh/message-analysis.git
    targetRevision: HEAD
    path: ./manifests/helm/app
    helm:
      parameters:
      - name: namespace.name
        value: message-analysis-dev
      - name: environment
        value: dev
      - name: image.tag
        value: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: message-analysis-dev
  ignoreDifferences:
    - group: '*'
      jqPathExpressions:
        - '.imagePullSecrets[] | select(.name | contains("-dockercfg-"))'
      kind: ServiceAccount
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: -1
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 2m # the maximum amount of time allowed for the backoff strategy
